In [1]:
# import pandaa and Numpy
import pandas as pd
import numpy as np

In [2]:
# Read csv files
df = pd.read_csv('X_Result.csv')

In [17]:
df.head()

,ID,BANCQ,BAN20,EngCQ,Eng20,GMathCQ,GMath20,BGSCQ,BGS20,ReliCQ,...,ReliGL,GMathTTL,GMathGP,GMathGL,EngTTL,EngGP,EngGL,BANTTL,BANGP,BANGL
0,1.0,20.0,8.0,10.0,15.0,27.0,7.0,20.0,14.0,23.0,...,A-,34.0,3.5,A-,25.0,3.0,B,28.0,3.0,B
1,2.0,21.0,11.0,15.0,18.0,27.0,7.0,19.0,10.0,29.0,...,A+,34.0,3.5,A-,33.0,3.5,A-,32.0,3.5,A-
2,3.0,16.0,6.0,6.0,6.0,0.0,0.0,11.0,0.0,17.0,...,B,0.0,0.0,F,12.0,0.0,F,22.0,2.0,C
3,4.0,15.0,8.0,17.0,15.0,18.0,8.0,20.0,12.0,25.0,...,A,26.0,3.0,B,32.0,3.5,A-,23.0,2.0,C
4,5.0,26.0,13.0,18.0,11.0,29.0,7.0,25.0,13.0,29.0,...,A,36.0,4.0,A,29.0,3.0,B,39.0,4.0,A

In [20]:
# Sum Two Column, Make Grade point and Later Grade on new Sum
df['CheTTL'] = df['CheCQ']+df['Che20']
df['CheGP'] =np.where(df['CheTTL']>39, 5, np.where(df['CheTTL']>34, 4,np.where(df['CheTTL']>29, 3.5,np.where(df['CheTTL']>24, 3, np.where(df['CheTTL']>19, 2,0)))))
df['CheGL'] =np.where(df['CheGP']==5, 'A+', np.where(df['CheGP']==4, 'A',np.where(df['CheGP']==3.5, 'A-',np.where(df['CheGP']==3, 'B', np.where(df['CheGP']==2, 'C','F')))))

In [19]:
df = df.round({'GPA': 2})
df.head()

,ID,BANCQ,BAN20,ENGCQ,ENG20,MathCQ,Math20,BGSCQ,BGS20,ReliCQ,...,CheGL,BioTTL,BioGP,BioGL,HMTTL,HMGP,HMGL,TTLMark,GPGPA,GPA
0,1,23,16,20,19,30,18,27,18,29,...,A+,44,5.0,A+,43,5.0,A+,383,42.0,4.67
1,2,22,12,18,10,30,6,27,8,29,...,A+,41,5.0,A+,15,0.0,F,316,33.5,3.72
2,3,0,8,0,7,0,19,0,17,0,...,F,16,0.0,F,11,0.0,F,119,0.0,0.00
3,4,23,17,21,17,28,9,14,12,0,...,A,21,2.0,C,5,0.0,F,220,22.0,2.44
4,5,24,17,26,13,29,14,22,16,29,...,A+,41,5.0,A+,44,5.0,A+,376,42.0,4.67

In [3]:
df.head()

,ID,BANCQ,BAN20,BanTTL,BanGP,BanGL,ENGCQ,ENG20,EngTTL,EngGP,...,HM20,HMTTL,HMGP,HMGL,TTLMark,Per,TTLGPA,GPA,LG,Position
0,43,24.0,16.0,40.0,5.0,A+,22.0,19.0,41.0,5.0,...,19.0,43.0,5.0,A+,381.0,84.67,44.0,4.89,A,1
1,7,25.0,13.0,38.0,4.0,A,25.0,15.0,40.0,5.0,...,18.0,46.0,5.0,A+,386.0,85.78,43.0,4.78,A,2
2,17,25.0,15.0,40.0,5.0,A+,17.0,12.0,29.0,3.0,...,15.0,43.0,5.0,A+,383.0,85.11,43.0,4.78,A,3
3,6,25.0,16.0,41.0,5.0,A+,20.0,15.0,35.0,4.0,...,15.0,45.0,5.0,A+,382.0,84.89,43.0,4.78,A,4
4,1,23.0,16.0,39.0,4.0,A,20.0,19.0,39.0,4.0,...,15.0,43.0,5.0,A+,383.0,85.11,42.0,4.67,A,5

In [21]:
df.head()

,ID,BANCQ,BAN20,ENGCQ,ENG20,MathCQ,Math20,BGSCQ,BGS20,ReliCQ,...,CheGL,BioTTL,BioGP,BioGL,HMTTL,HMGP,HMGL,TTLMark,GPGPA,GPA
36,43,24,16,22,19,24,14,27,17,29,...,A+,43,5.0,A+,43,5.0,A+,381,44.0,4.89
6,7,25,13,25,15,30,17,26,10,29,...,A+,46,5.0,A+,46,5.0,A+,386,43.0,4.78
15,17,25,15,17,12,30,15,27,15,28,...,A+,46,5.0,A+,43,5.0,A+,383,43.0,4.78
5,6,25,16,20,15,30,17,24,15,29,...,A+,42,5.0,A+,45,5.0,A+,382,43.0,4.78
0,1,23,16,20,19,30,18,27,18,29,...,A+,44,5.0,A+,43,5.0,A+,383,42.0,4.67

In [21]:
cols = df.columns.tolist()
cols

['ID',
 'BANCQ',
 'BAN20',
 'EngCQ',
 'Eng20',
 'GMathCQ',
 'GMath20',
 'BGSCQ',
 'BGS20',
 'ReliCQ',
 'Reli20',
 'PhyCQ',
 'Phy20',
 'CheCQ',
 'Che20',
 'BioCQ',
 'Bio20',
 'ICT25',
 'HMCQ',
 'HM20',
 'HMTTL',
 'HMGP',
 'HMGL',
 'ICTGP',
 'ICTGL',
 'BioTTL',
 'BioGP',
 'BioGL',
 'PhyTTL',
 'PhyGP',
 'PhyGL',
 'BGSTTL',
 'BGSGP',
 'BGSGL',
 'ReliTTL',
 'ReliGP',
 'ReliGL',
 'GMathTTL',
 'GMathGP',
 'GMathGL',
 'EngTTL',
 'EngGP',
 'EngGL',
 'BANTTL',
 'BANGP',
 'BANGL',
 'CheTTL',
 'CheGP',
 'CheGL']

In [23]:
#Grand Total of All Subject Total
df['TTLMark'] = df['BANTTL']+df['EngTTL']+df['GMathTTL']+df['BGSTTL']+df['ReliTTL']+df['PhyTTL']+df['CheTTL']+df['BioTTL']+df['ICT25']+df['HMTTL']

In [24]:
df['TTLGP'] = df['BANGP']+df['EngGP']+df['GMathGP']+df['BGSGP']+df['ReliGP']+df['PhyGP']+df['CheGP']+df['BioGP']+df['ICTGP']+df['HMGP']

In [26]:
df['AGP']=df['TTLGP']/10
df['LG'] =np.where(df['AGP']>=5, 'A+', np.where(df['AGP']>=4, 'A',np.where(df['AGP']>=3.5, 'A-',np.where(df['AGP']>=3, 'B', np.where(df['AGP']>=2, 'C','F')))))

In [28]:
df = df.sort_values(by=['TTLGP', 'TTLMark'], ascending=[False, False])

In [29]:
# Add Serial Number
df['Position'] = range(1, 1+len(df))

In [23]:
df

,ID,BANCQ,BAN20,ENGCQ,ENG20,MathCQ,Math20,BGSCQ,BGS20,ReliCQ,...,BioTTL,BioGP,BioGL,HMTTL,HMGP,HMGL,TTLMark,GPGPA,GPA,Position
36,43,24,16,22,19,24,14,27,17,29,...,43,5.0,A+,43,5.0,A+,381,44.0,4.89,1
6,7,25,13,25,15,30,17,26,10,29,...,46,5.0,A+,46,5.0,A+,386,43.0,4.78,2
15,17,25,15,17,12,30,15,27,15,28,...,46,5.0,A+,43,5.0,A+,383,43.0,4.78,3
5,6,25,16,20,15,30,17,24,15,29,...,42,5.0,A+,45,5.0,A+,382,43.0,4.78,4
0,1,23,16,20,19,30,18,27,18,29,...,44,5.0,A+,43,5.0,A+,383,42.0,4.67,5
23,26,20,13,19,15,30,19,24,17,29,...,43,5.0,A+,47,5.0,A+,380,42.0,4.67,6
4,5,24,17,26,13,29,14,22,16,29,...,41,5.0,A+,44,5.0,A+,376,42.0,4.67,7
11,13,23,13,22,17,29,18,23,11,28,...,43,5.0,A+,38,4.0,A,363,40.5,4.50,8
10,12,25,11,27,14,30,9,27,11,29,...,41,5.0,A+,38,4.0,A,359,40.0,4.44,9
21,24,20,15,20,17,24,18,17,15,28,...,37,4.0,A,41,5.0,A+,349,39.5,4.39,10
12,14,24,14,18,13,30,10,25,15,26,...,40,5.0,A+,34,3.5,A-,339,39.5,4.39,11
7,8,23,10,19,6,30,11,27,18,28,...,39,4.0,A,35,4.0,A,341,38.5,4.28,12
34,40,25,12,28,14,29,9,27,17,29,...,37,4.0,A,24,2.0,C,351,38.0,4.22,13
28,31,18,16,15,10,26,5,26,16,29,...,38,4.0,A,48,5.0,A+,346,38.0,4.22,14
19,22,25,13,21,16,30,14,22,13,29,...,38,4.0,A,40,5.0,A+,337,38.0,4.22,15
24,27,23,18,22,16,19,16,20,18,27,...,32,3.5,A-,38,4.0,A,336,37.5,4.17,16
31,36,26,8,19,7,28,8,27,10,29,...,41,5.0,A+,35,4.0,A,332,37.5,4.17,17
37,44,23,15,24,14,24,8,24,12,29,...,34,3.5,A-,31,3.5,A-,327,36.0,4.00,18
14,16,22,0,21,7,30,8,20,17,29,...,41,5.0,A+,35,4.0,A,309,34.5,3.83,19
1,2,22,12,18,10,30,6,27,8,29,...,41,5.0,A+,15,0.0,F,316,33.5,3.72,20
25,28,21,11,17,10,30,3,25,12,24,...,26,3.0,B,36,4.0,A,303,33.0,3.67,21
20,23,20,12,18,11,30,3,20,17,23,...,38,4.0,A,30,3.5,A-,298,32.0,3.56,22
13,15,24,14,17,9,27,10,23,13,29,...,33,3.5,A-,31,3.5,A-,286,30.0,3.33,23
16,18,21,8,25,7,25,7,17,11,28,...,30,3.5,A-,36,4.0,A,277,30.0,3.33,24
8,10,20,12,15,10,20,11,25,15,26,...,29,3.0,B,28,3.0,B,268,29.0,3.22,25
22,25,16,14,13,0,12,9,17,14,29,...,33,3.5,A-,37,4.0,A,275,28.5,3.17,26
9,11,23,15,14,10,26,9,26,10,29,...,33,3.5,A-,10,0.0,F,270,28.0,3.11,27
32,37,15,14,17,16,18,10,14,17,24,...,19,0.0,F,31,3.5,A-,266,26.5,2.94,28
27,30,22,11,16,14,20,15,18,10,16,...,37,4.0,A,18,0.0,F,264,26.5,2.94,29
3,4,23,17,21,17,28,9,14,12,0,...,21,2.0,C,5,0.0,F,220,22.0,2.44,30
35,42,15,7,17,7,25,0,10,11,25,...,10,0.0,F,25,3.0,B,213,21.5,2.39,31
30,34,16,9,14,9,22,7,8,15,18,...,19,0.0,F,24,2.0,C,205,15.0,1.67,32
29,33,11,8,14,9,27,6,14,7,11,...,15,0.0,F,21,2.0,C,170,11.5,1.28,33
33,39,0,7,0,13,0,12,20,16,0,...,0,0.0,F,45,5.0,A+,120,9.0,1.00,34
18,20,0,14,0,18,0,19,19,14,0,...,17,0.0,F,20,2.0,C,171,5.5,0.61,35
17,19,13,14,2,7,0,13,2,18,2,...,18,0.0,F,6,0.0,F,127,5.0,0.56,36
26,29,0,14,0,15,0,13,0,12,0,...,20,2.0,C,19,0.0,F,140,2.0,0.22,37
2,3,0,8,0,7,0,19,0,17,0,...,16,0.0,F,11,0.0,F,119,0.0,0.00,38

In [59]:
# Delete Column
del df['Per']

In [35]:
df.head()

,ID,BANCQ,BAN20,ENGCQ,ENG20,BGSCQ,BGS20,MathCQ,Math20,PhyCQ,...,CheTTL,CheGP,CheGL,MathTTL,MathGP,MathGL,TTLMark,TTLGPA,GPA,LG
0,1,23.0,16.0,20.0,19.0,27.0,18.0,30.0,18.0,24.0,...,41.0,5.0,A+,48.0,5.0,A+,383.0,42.0,4.666667,A
1,2,22.0,12.0,18.0,10.0,27.0,8.0,30.0,6.0,27.0,...,43.0,5.0,A+,36.0,4.0,A,NaN,33.5,3.722222,A-
2,3,NaN,8.0,NaN,7.0,NaN,17.0,NaN,19.0,NaN,...,NaN,0.0,F,NaN,0.0,F,NaN,0.0,0.000000,F
3,4,23.0,17.0,21.0,17.0,14.0,12.0,28.0,9.0,16.0,...,37.0,4.0,A,37.0,4.0,A,NaN,22.0,2.444444,C
4,5,24.0,17.0,26.0,13.0,22.0,16.0,29.0,14.0,27.0,...,47.0,5.0,A+,43.0,5.0,A+,376.0,42.0,4.666667,A

In [46]:
cols = df.columns.tolist()
cols

['ID',
 'BANCQ',
 'BAN20',
 'ENGCQ',
 'ENG20',
 'BGSCQ',
 'BGS20',
 'MathCQ',
 'Math20',
 'PhyCQ',
 'Phy20',
 'HMCQ',
 'HM20',
 'BioCQ',
 'Bio20',
 'ReliCQ',
 'Reli20',
 'CheCQ',
 'Che20',
 'BanTTL',
 'BanGP',
 'BanGL',
 'EngTTL',
 'EngGP',
 'EngGL',
 'BGSTTL',
 'BGSGP',
 'BGSGL',
 'PhyTTL',
 'PhyGP',
 'PhyGL',
 'HMTTL',
 'HMGP',
 'HMGL',
 'BioTTL',
 'BioGP',
 'BioGL',
 'ReliTTL',
 'ReliGP',
 'ReliGL',
 'CheTTL',
 'CheGP',
 'CheGL',
 'MathTTL',
 'MathGP',
 'MathGL',
 'TTLMark',
 'TTLGPA',
 'GPA',
 'LG',
 'Position']

In [52]:
# Rearrange Columns 
df = df[['ID', 'BANCQ', 'BAN20','BanTTL', 'BanGP', 'BanGL',
         'ENGCQ', 'ENG20','EngTTL', 'EngGP', 'EngGL',
         'MathCQ',  'Math20','MathTTL', 'MathGP', 'MathGL',
         'BGSCQ', 'BGS20','BGSTTL',  'BGSGP', 'BGSGL',
         'ReliCQ', 'Reli20', 'ReliTTL', 'ReliGP',  'ReliGL',
         'PhyCQ', 'Phy20', 'PhyTTL', 'PhyGP', 'PhyGL',
         'CheCQ', 'Che20', 'CheTTL',  'CheGP',  'CheGL',
         'BioCQ', 'Bio20', 'BioTTL',  'BioGP', 'BioGL',
         'HMCQ', 'HM20', 'HMTTL', 'HMGP', 'HMGL',
         'TTLMark','Per', 'TTLGPA', 'GPA', 'LG', 'Position']]

In [30]:
df.to_csv('X_Final.csv', index = False)

In [57]:
pd.options.display.float_format = "{:,.0f}".format # Two precision point

In [58]:
df.head()

,ID,BANCQ,BAN20,BanTTL,BanGP,BanGL,ENGCQ,ENG20,EngTTL,EngGP,...,HM20,HMTTL,HMGP,HMGL,TTLMark,Per,TTLGPA,GPA,LG,Position
36,43,24,16,40,5,A+,22,19,41,5,...,19,43,5,A+,381,85,44,5,A,1
6,7,25,13,38,4,A,25,15,40,5,...,18,46,5,A+,386,86,43,5,A,2
15,17,25,15,40,5,A+,17,12,29,3,...,15,43,5,A+,383,85,43,5,A,3
5,6,25,16,41,5,A+,20,15,35,4,...,15,45,5,A+,382,85,43,5,A,4
0,1,23,16,39,4,A,20,19,39,4,...,15,43,5,A+,383,85,42,5,A,5

In [62]:
df['Per'] = df['TTLMark'] /450 * 100
df.round({'Per': 2})

,ID,BANCQ,BAN20,BanTTL,BanGP,BanGL,ENGCQ,ENG20,EngTTL,EngGP,...,HM20,HMTTL,HMGP,HMGL,TTLMark,Per,TTLGPA,GPA,LG,Position
0,43,24,16,40,5,A+,22,19,41,5,...,19,43,5,A+,381,85,44,5,A,1
1,7,25,13,38,4,A,25,15,40,5,...,18,46,5,A+,386,86,43,5,A,2
2,17,25,15,40,5,A+,17,12,29,3,...,15,43,5,A+,383,85,43,5,A,3
3,6,25,16,41,5,A+,20,15,35,4,...,15,45,5,A+,382,85,43,5,A,4
4,1,23,16,39,4,A,20,19,39,4,...,15,43,5,A+,383,85,42,5,A,5
5,26,20,13,33,4,A-,19,15,34,4,...,19,47,5,A+,380,84,42,5,A,6
6,5,24,17,41,5,A+,26,13,39,4,...,16,44,5,A+,376,84,42,5,A,7
7,12,25,11,36,4,A,27,14,41,5,...,9,38,4,A,359,80,40,4,A,8
8,24,20,15,35,4,A,20,17,37,4,...,13,41,5,A+,349,78,40,4,A,9
9,14,24,14,38,4,A,18,13,31,4,...,13,34,4,A-,339,75,40,4,A,10
10,31,18,16,34,4,A-,15,10,25,3,...,18,48,5,A+,346,77,38,4,A,11
11,44,23,15,38,4,A,24,14,38,4,...,7,31,4,A-,327,73,36,4,A,12
12,40,25,12,37,4,A,28,14,42,5,...,9,NaN,0,F,NaN,NaN,36,4,A,13
13,8,23,10,33,4,A-,19,6,25,3,...,12,35,4,A,NaN,NaN,34,4,A-,14
14,22,25,13,38,4,A,21,16,37,4,...,11,40,5,A+,NaN,NaN,34,4,A-,15
15,2,22,12,34,4,A-,18,10,28,3,...,NaN,NaN,0,F,NaN,NaN,34,4,A-,16
16,36,26,8,34,4,A-,19,7,26,3,...,7,35,4,A,NaN,NaN,34,4,A-,17
17,28,21,11,32,4,A-,17,10,27,3,...,11,36,4,A,303,67,33,4,A-,18
18,16,22,NaN,NaN,0,F,21,7,28,3,...,9,35,4,A,NaN,NaN,32,4,A-,19
19,27,23,18,41,5,A+,22,16,38,4,...,14,38,4,A,NaN,NaN,32,4,A-,20
20,13,23,13,36,4,A,22,17,39,4,...,14,38,4,A,NaN,NaN,30,3,B,21
21,15,24,14,38,4,A,17,9,26,3,...,6,31,4,A-,286,64,30,3,B,22
22,18,21,8,29,3,B,25,7,32,4,...,9,36,4,A,277,62,30,3,B,23
23,10,20,12,32,4,A-,15,10,25,3,...,9,28,3,B,268,60,29,3,B,24
24,23,20,12,32,4,A-,18,11,29,3,...,6,30,4,A-,NaN,NaN,29,3,B,25
25,25,16,14,30,4,A-,13,NaN,NaN,0,...,12,37,4,A,NaN,NaN,28,3,B,26
26,11,23,15,38,4,A,14,10,24,2,...,10,10,0,F,270,60,28,3,B,27
27,30,22,11,33,4,A-,16,14,30,4,...,9,18,0,F,264,59,26,3,C,28
28,37,15,14,29,3,B,17,16,33,4,...,13,31,4,A-,NaN,NaN,24,3,C,29
29,4,23,17,40,5,A+,21,17,38,4,...,NaN,NaN,0,F,NaN,NaN,22,2,C,30
30,33,11,8,19,0,F,14,9,23,2,...,9,21,2,C,NaN,NaN,12,1,F,31
31,42,15,7,22,2,C,17,7,24,2,...,NaN,NaN,0,F,NaN,NaN,10,1,F,32
32,39,NaN,7,NaN,0,F,NaN,13,NaN,0,...,16,45,5,A+,NaN,NaN,9,1,F,33
33,34,16,9,25,3,B,14,9,23,2,...,6,NaN,0,F,NaN,NaN,7,1,F,34
34,20,NaN,14,NaN,0,F,NaN,18,NaN,0,...,20,NaN,0,F,NaN,NaN,4,0,F,35
35,19,13,14,27,3,B,NaN,7,NaN,0,...,6,NaN,0,F,NaN,NaN,3,0,F,36
36,3,NaN,8,NaN,0,F,NaN,7,NaN,0,...,11,NaN,0,F,NaN,NaN,0,0,F,37
37,29,NaN,14,NaN,0,F,NaN,15,NaN,0,...,19,NaN,0,F,NaN,NaN,0,0,F,38

In [13]:
df.head()

,ID,BANCQ,BAN20,BanTTL,BanGP,BanGL,ENGCQ,ENG20,EngTTL,EngGP,...,HM20,HMTTL,HMGP,HMGL,TTLMark,Per,TTLGPA,GPA,LG,Position
0,43,24.0,16.0,40.0,5.0,A+,22.0,19.0,41.0,5.0,...,19.0,43.0,5.0,A+,381.0,84.67,44.0,4.89,A,1
1,7,25.0,13.0,38.0,4.0,A,25.0,15.0,40.0,5.0,...,18.0,46.0,5.0,A+,386.0,85.78,43.0,4.78,A,2
2,17,25.0,15.0,40.0,5.0,A+,17.0,12.0,29.0,3.0,...,15.0,43.0,5.0,A+,383.0,85.11,43.0,4.78,A,3
3,6,25.0,16.0,41.0,5.0,A+,20.0,15.0,35.0,4.0,...,15.0,45.0,5.0,A+,382.0,84.89,43.0,4.78,A,4
4,1,23.0,16.0,39.0,4.0,A,20.0,19.0,39.0,4.0,...,15.0,43.0,5.0,A+,383.0,85.11,42.0,4.67,A,5

In [16]:
# Create Message
for (row, rowseries) in df.iterrows():
    #print(row)
    #print(rowseries)
    message = ''' 
                    HOLY LAND College
                    1st Term Mark Sheet-2021
                   .......................... 
    Id: {} of Clas IX        Obtain postion: {}
    {} : {}, {} : {}, {} : {}, {} : {}, {} : {}    
    {} : {}, {} : {}, {} : {}, {} : {}, {} : {}    
    {} : {}, {} : {}, {} : {}, {} : {}, {} : {}    
    {} : {}, {} : {}, {} : {}, {} : {}, {} : {}
    {} : {}, {} : {}, {} : {}, {} : {}, {} : {}    
    {} : {}, {} : {}, {} : {}, {} : {}, {} : {}  
    {} : {}, {} : {}, {} : {}, {} : {}, {} : {}    
    {} : {}, {} : {}, {} : {}, {} : {}, {} : {}
    {} : {}, {} : {}, {} : {}, {} : {}, {} : {}    
    {} : {}, {} : {}, {} : {}, {} : {}, {} : {} 
            
    '''.format(rowseries[0], rowseries[51],
               rowseries.index[1],rowseries[1],
               rowseries.index[2],rowseries[2],  
               rowseries.index[3],rowseries[3], 
               rowseries.index[4],rowseries[4], 
               rowseries.index[5],rowseries[5],
               rowseries.index[6],rowseries[6],
               rowseries.index[7],rowseries[7],  
               rowseries.index[8],rowseries[8], 
                rowseries.index[9],rowseries[9], 
               rowseries.index[10],rowseries[10],
                rowseries.index[11],rowseries[11],
               rowseries.index[12],rowseries[12],  
               rowseries.index[13],rowseries[13], 
               rowseries.index[14],rowseries[14], 
               rowseries.index[15],rowseries[15],
               rowseries.index[16],rowseries[16],
               rowseries.index[17],rowseries[17],  
               rowseries.index[18],rowseries[18], 
                rowseries.index[19],rowseries[19], 
               rowseries.index[20],rowseries[20],
                rowseries.index[21],rowseries[21],
               rowseries.index[22],rowseries[22],  
               rowseries.index[23],rowseries[23], 
               rowseries.index[24],rowseries[24], 
               rowseries.index[25],rowseries[25],
               rowseries.index[26],rowseries[26],
               rowseries.index[27],rowseries[27],  
               rowseries.index[28],rowseries[28], 
                rowseries.index[29],rowseries[29], 
               rowseries.index[30],rowseries[30],
               rowseries.index[31],rowseries[31],
               rowseries.index[32],rowseries[32],  
               rowseries.index[33],rowseries[33], 
               rowseries.index[34],rowseries[34], 
               rowseries.index[35],rowseries[35],
               rowseries.index[36],rowseries[36],
               rowseries.index[37],rowseries[37],  
               rowseries.index[38],rowseries[38], 
                rowseries.index[39],rowseries[39], 
               rowseries.index[40],rowseries[40],
                rowseries.index[41],rowseries[41],
               rowseries.index[42],rowseries[42],  
               rowseries.index[43],rowseries[43], 
               rowseries.index[44],rowseries[44], 
               rowseries.index[45],rowseries[45],
               rowseries.index[46],rowseries[46],
               rowseries.index[47],rowseries[47],  
               rowseries.index[48],rowseries[48],
               rowseries.index[49],rowseries[49], 
               rowseries.index[50],rowseries[50])
    print(message)

                    HOLY LAND College
                    1st Term Mark Sheet-2021
                   ..........................
    Id: 43 of Clas IX        Obtain postion: 1
    BANCQ : 24.0, BAN20 : 16.0, BanTTL : 40.0, BanGP : 5.0, BanGL : A+
    ENGCQ : 22.0, ENG20 : 19.0, EngTTL : 41.0, EngGP : 5.0, EngGL : A+
    MathCQ : 24.0, Math20 : 14.0, MathTTL : 38.0, MathGP : 4.0, MathGL : A
    BGSCQ : 27.0, BGS20 : 17.0, BGSTTL : 44.0, BGSGP : 5.0, BGSGL : A+
    ReliCQ : 29.0, Reli20 : 17.0, ReliTTL : 46.0, ReliGP : 5.0, ReliGL : A+
    PhyCQ : 27.0, Phy20 : 13.0, PhyTTL : 40.0, PhyGP : 5.0, PhyGL : A+
    CheCQ : 28.0, Che20 : 18.0, CheTTL : 46.0, CheGP : 5.0, CheGL : A+
    BioCQ : 23.0, Bio20 : 20.0, BioTTL : 43.0, BioGP : 5.0, BioGL : A+
    HMCQ : 24.0, HM20 : 19.0, HMTTL : 43.0, HMGP : 5.0, HMGL : A+
    TTLMark : 381.0, Per : 84.67, TTLGPA : 44.0, GPA : 4.89, LG : A



                    HOLY LAND College
                    1st Term Mark Sheet-2021
                   ..........................
    Id: 7 of Clas IX        Obtain postion: 2
    BANCQ : 25.0, BAN20 : 13.0, BanTTL : 38.0, BanGP : 4.0, BanGL : A
    ENGCQ : 25.0, ENG20 : 15.0, EngTTL : 40.0, EngGP : 5.0, EngGL : A+
    MathCQ : 30.0, Math20 : 17.0, MathTTL : 47.0, MathGP : 5.0, MathGL : A+
    BGSCQ : 26.0, BGS20 : 10.0, BGSTTL : 36.0, BGSGP : 4.0, BGSGL : A
    ReliCQ : 29.0, Reli20 : 16.0, ReliTTL : 45.0, ReliGP : 5.0, ReliGL : A+
    PhyCQ : 30.0, Phy20 : 14.0, PhyTTL : 44.0, PhyGP : 5.0, PhyGL : A+
    CheCQ : 28.0, Che20 : 16.0, CheTTL : 44.0, CheGP : 5.0, CheGL : A+
    BioCQ : 30.0, Bio20 : 16.0, BioTTL : 46.0, BioGP : 5.0, BioGL : A+
    HMCQ : 28.0, HM20 : 18.0, HMTTL : 46.0, HMGP : 5.0, HMGL : A+
    TTLMark : 386.0, Per : 85.78, TTLGPA : 43.0, GPA : 4.78, LG : A



                    HOLY LAND College
                    1st Term Mark Sheet-2021
                   ..........................
    Id: 17 of Clas IX        Obtain postion: 3
    BANCQ : 25.0, BAN20 : 15.0, BanTTL : 40.0, BanGP : 5.0, BanGL : A+
    ENGCQ : 17.0, ENG20 : 12.0, EngTTL : 29.0, EngGP : 3.0, EngGL : B
    MathCQ : 30.0, Math20 : 15.0, MathTTL : 45.0, MathGP : 5.0, MathGL : A+
    BGSCQ : 27.0, BGS20 : 15.0, BGSTTL : 42.0, BGSGP : 5.0, BGSGL : A+
    ReliCQ : 28.0, Reli20 : 17.0, ReliTTL : 45.0, ReliGP : 5.0, ReliGL : A+
    PhyCQ : 30.0, Phy20 : 15.0, PhyTTL : 45.0, PhyGP : 5.0, PhyGL : A+
    CheCQ : 28.0, Che20 : 20.0, CheTTL : 48.0, CheGP : 5.0, CheGL : A+
    BioCQ : 28.0, Bio20 : 18.0, BioTTL : 46.0, BioGP : 5.0, BioGL : A+
    HMCQ : 28.0, HM20 : 15.0, HMTTL : 43.0, HMGP : 5.0, HMGL : A+
    TTLMark : 383.0, Per : 85.11, TTLGPA : 43.0, GPA : 4.78, LG : A



                    HOLY LAND College
                    1st Term Mark Sheet-2021
                   ..........................
    Id: 6 of Clas IX        Obtain postion: 4
    BANCQ : 25.0, BAN20 : 16.0, BanTTL : 41.0, BanGP : 5.0, BanGL : A+
    ENGCQ : 20.0, ENG20 : 15.0, EngTTL : 35.0, EngGP : 4.0, EngGL : A
    MathCQ : 30.0, Math20 : 17.0, MathTTL : 47.0, MathGP : 5.0, MathGL : A+
    BGSCQ : 24.0, BGS20 : 15.0, BGSTTL : 39.0, BGSGP : 4.0, BGSGL : A
    ReliCQ : 29.0, Reli20 : 17.0, ReliTTL : 46.0, ReliGP : 5.0, ReliGL : A+
    PhyCQ : 29.0, Phy20 : 14.0, PhyTTL : 43.0, PhyGP : 5.0, PhyGL : A+
    CheCQ : 29.0, Che20 : 15.0, CheTTL : 44.0, CheGP : 5.0, CheGL : A+
    BioCQ : 24.0, Bio20 : 18.0, BioTTL : 42.0, BioGP : 5.0, BioGL : A+
    HMCQ : 30.0, HM20 : 15.0, HMTTL : 45.0, HMGP : 5.0, HMGL : A+
    TTLMark : 382.0, Per : 84.89, TTLGPA : 43.0, GPA : 4.78, LG : A



                    HOLY LAND College
                    1st Term Mark Sheet-2021
                   ..........................
    Id: 1 of Clas IX        Obtain postion: 5
    BANCQ : 23.0, BAN20 : 16.0, BanTTL : 39.0, BanGP : 4.0, BanGL : A
    ENGCQ : 20.0, ENG20 : 19.0, EngTTL : 39.0, EngGP : 4.0, EngGL : A
    MathCQ : 30.0, Math20 : 18.0, MathTTL : 48.0, MathGP : 5.0, MathGL : A+
    BGSCQ : 27.0, BGS20 : 18.0, BGSTTL : 45.0, BGSGP : 5.0, BGSGL : A+
    ReliCQ : 29.0, Reli20 : 20.0, ReliTTL : 49.0, ReliGP : 5.0, ReliGL : A+
    PhyCQ : 24.0, Phy20 : 11.0, PhyTTL : 35.0, PhyGP : 4.0, PhyGL : A
    CheCQ : 22.0, Che20 : 19.0, CheTTL : 41.0, CheGP : 5.0, CheGL : A+
    BioCQ : 26.0, Bio20 : 18.0, BioTTL : 44.0, BioGP : 5.0, BioGL : A+
    HMCQ : 28.0, HM20 : 15.0, HMTTL : 43.0, HMGP : 5.0, HMGL : A+
    TTLMark : 383.0, Per : 85.11, TTLGPA : 42.0, GPA : 4.67, LG : A



                    HOLY LAND College
                    1st Term Mark Sheet-2021
                   ..........................
    Id: 26 of Clas IX        Obtain postion: 6
    BANCQ : 20.0, BAN20 : 13.0, BanTTL : 33.0, BanGP : 3.5, BanGL : A-
    ENGCQ : 19.0, ENG20 : 15.0, EngTTL : 34.0, EngGP : 3.5, EngGL : A-
    MathCQ : 30.0, Math20 : 19.0, MathTTL : 49.0, MathGP : 5.0, MathGL : A+
    BGSCQ : 24.0, BGS20 : 17.0, BGSTTL : 41.0, BGSGP : 5.0, BGSGL : A+
    ReliCQ : 29.0, Reli20 : 14.0, ReliTTL : 43.0, ReliGP : 5.0, ReliGL : A+
    PhyCQ : 28.0, Phy20 : 17.0, PhyTTL : 45.0, PhyGP : 5.0, PhyGL : A+
    CheCQ : 28.0, Che20 : 17.0, CheTTL : 45.0, CheGP : 5.0, CheGL : A+
    BioCQ : 24.0, Bio20 : 19.0, BioTTL : 43.0, BioGP : 5.0, BioGL : A+
    HMCQ : 28.0, HM20 : 19.0, HMTTL : 47.0, HMGP : 5.0, HMGL : A+
    TTLMark : 380.0, Per : 84.44, TTLGPA : 42.0, GPA : 4.67, LG : A



                    HOLY LAND College
                    1st Term Mark Sheet-2021
                   ..........................
    Id: 5 of Clas IX        Obtain postion: 7
    BANCQ : 24.0, BAN20 : 17.0, BanTTL : 41.0, BanGP : 5.0, BanGL : A+
    ENGCQ : 26.0, ENG20 : 13.0, EngTTL : 39.0, EngGP : 4.0, EngGL : A
    MathCQ : 29.0, Math20 : 14.0, MathTTL : 43.0, MathGP : 5.0, MathGL : A+
    BGSCQ : 22.0, BGS20 : 16.0, BGSTTL : 38.0, BGSGP : 4.0, BGSGL : A
    ReliCQ : 29.0, Reli20 : 18.0, ReliTTL : 47.0, ReliGP : 5.0, ReliGL : A+
    PhyCQ : 27.0, Phy20 : 9.0, PhyTTL : 36.0, PhyGP : 4.0, PhyGL : A
    CheCQ : 29.0, Che20 : 18.0, CheTTL : 47.0, CheGP : 5.0, CheGL : A+
    BioCQ : 25.0, Bio20 : 16.0, BioTTL : 41.0, BioGP : 5.0, BioGL : A+
    HMCQ : 28.0, HM20 : 16.0, HMTTL : 44.0, HMGP : 5.0, HMGL : A+
    TTLMark : 376.0, Per : 83.56, TTLGPA : 42.0, GPA : 4.67, LG : A



                    HOLY LAND College
                    1st Term Mark Sheet-2021
                   ..........................
    Id: 12 of Clas IX        Obtain postion: 8
    BANCQ : 25.0, BAN20 : 11.0, BanTTL : 36.0, BanGP : 4.0, BanGL : A
    ENGCQ : 27.0, ENG20 : 14.0, EngTTL : 41.0, EngGP : 5.0, EngGL : A+
    MathCQ : 30.0, Math20 : 9.0, MathTTL : 39.0, MathGP : 4.0, MathGL : A
    BGSCQ : 27.0, BGS20 : 11.0, BGSTTL : 38.0, BGSGP : 4.0, BGSGL : A
    ReliCQ : 29.0, Reli20 : 16.0, ReliTTL : 45.0, ReliGP : 5.0, ReliGL : A+
    PhyCQ : 26.0, Phy20 : 11.0, PhyTTL : 37.0, PhyGP : 4.0, PhyGL : A
    CheCQ : 28.0, Che20 : 16.0, CheTTL : 44.0, CheGP : 5.0, CheGL : A+
    BioCQ : 27.0, Bio20 : 14.0, BioTTL : 41.0, BioGP : 5.0, BioGL : A+
    HMCQ : 29.0, HM20 : 9.0, HMTTL : 38.0, HMGP : 4.0, HMGL : A
    TTLMark : 359.0, Per : 79.78, TTLGPA : 40.0, GPA : 4.44, LG : A



                    HOLY LAND College
                    1st Term Mark Sheet-2021
                   ..........................
    Id: 24 of Clas IX        Obtain postion: 9
    BANCQ : 20.0, BAN20 : 15.0, BanTTL : 35.0, BanGP : 4.0, BanGL : A
    ENGCQ : 20.0, ENG20 : 17.0, EngTTL : 37.0, EngGP : 4.0, EngGL : A
    MathCQ : 24.0, Math20 : 18.0, MathTTL : 42.0, MathGP : 5.0, MathGL : A+
    BGSCQ : 17.0, BGS20 : 15.0, BGSTTL : 32.0, BGSGP : 3.5, BGSGL : A-
    ReliCQ : 28.0, Reli20 : 15.0, ReliTTL : 43.0, ReliGP : 5.0, ReliGL : A+
    PhyCQ : 25.0, Phy20 : 13.0, PhyTTL : 38.0, PhyGP : 4.0, PhyGL : A
    CheCQ : 25.0, Che20 : 19.0, CheTTL : 44.0, CheGP : 5.0, CheGL : A+
    BioCQ : 22.0, Bio20 : 15.0, BioTTL : 37.0, BioGP : 4.0, BioGL : A
    HMCQ : 28.0, HM20 : 13.0, HMTTL : 41.0, HMGP : 5.0, HMGL : A+
    TTLMark : 349.0, Per : 77.56, TTLGPA : 39.5, GPA : 4.39, LG : A



                    HOLY LAND College
                    1st Term Mark Sheet-2021
                   ..........................
    Id: 14 of Clas IX        Obtain postion: 10
    BANCQ : 24.0, BAN20 : 14.0, BanTTL : 38.0, BanGP : 4.0, BanGL : A
    ENGCQ : 18.0, ENG20 : 13.0, EngTTL : 31.0, EngGP : 3.5, EngGL : A-
    MathCQ : 30.0, Math20 : 10.0, MathTTL : 40.0, MathGP : 5.0, MathGL : A+
    BGSCQ : 25.0, BGS20 : 15.0, BGSTTL : 40.0, BGSGP : 5.0, BGSGL : A+
    ReliCQ : 26.0, Reli20 : 17.0, ReliTTL : 43.0, ReliGP : 5.0, ReliGL : A+
    PhyCQ : 24.0, Phy20 : 8.0, PhyTTL : 32.0, PhyGP : 3.5, PhyGL : A-
    CheCQ : 26.0, Che20 : 15.0, CheTTL : 41.0, CheGP : 5.0, CheGL : A+
    BioCQ : 28.0, Bio20 : 12.0, BioTTL : 40.0, BioGP : 5.0, BioGL : A+
    HMCQ : 21.0, HM20 : 13.0, HMTTL : 34.0, HMGP : 3.5, HMGL : A-
    TTLMark : 339.0, Per : 75.33, TTLGPA : 39.5, GPA : 4.39, LG : A



                    HOLY LAND College
                    1st Term Mark Sheet-2021
                   ..........................
    Id: 31 of Clas IX        Obtain postion: 11
    BANCQ : 18.0, BAN20 : 16.0, BanTTL : 34.0, BanGP : 3.5, BanGL : A-
    ENGCQ : 15.0, ENG20 : 10.0, EngTTL : 25.0, EngGP : 3.0, EngGL : B
    MathCQ : 26.0, Math20 : 5.0, MathTTL : 31.0, MathGP : 3.5, MathGL : A-
    BGSCQ : 26.0, BGS20 : 16.0, BGSTTL : 42.0, BGSGP : 5.0, BGSGL : A+
    ReliCQ : 29.0, Reli20 : 18.0, ReliTTL : 47.0, ReliGP : 5.0, ReliGL : A+
    PhyCQ : 27.0, Phy20 : 11.0, PhyTTL : 38.0, PhyGP : 4.0, PhyGL : A
    CheCQ : 26.0, Che20 : 17.0, CheTTL : 43.0, CheGP : 5.0, CheGL : A+
    BioCQ : 22.0, Bio20 : 16.0, BioTTL : 38.0, BioGP : 4.0, BioGL : A
    HMCQ : 30.0, HM20 : 18.0, HMTTL : 48.0, HMGP : 5.0, HMGL : A+
    TTLMark : 346.0, Per : 76.89, TTLGPA : 38.0, GPA : 4.22, LG : A



                    HOLY LAND College
                    1st Term Mark Sheet-2021
                   ..........................
    Id: 44 of Clas IX        Obtain postion: 12
    BANCQ : 23.0, BAN20 : 15.0, BanTTL : 38.0, BanGP : 4.0, BanGL : A
    ENGCQ : 24.0, ENG20 : 14.0, EngTTL : 38.0, EngGP : 4.0, EngGL : A
    MathCQ : 24.0, Math20 : 8.0, MathTTL : 32.0, MathGP : 3.5, MathGL : A-
    BGSCQ : 24.0, BGS20 : 12.0, BGSTTL : 36.0, BGSGP : 4.0, BGSGL : A
    ReliCQ : 29.0, Reli20 : 15.0, ReliTTL : 44.0, ReliGP : 5.0, ReliGL : A+
    PhyCQ : 28.0, Phy20 : 6.0, PhyTTL : 34.0, PhyGP : 3.5, PhyGL : A-
    CheCQ : 25.0, Che20 : 15.0, CheTTL : 40.0, CheGP : 5.0, CheGL : A+
    BioCQ : 18.0, Bio20 : 16.0, BioTTL : 34.0, BioGP : 3.5, BioGL : A-
    HMCQ : 24.0, HM20 : 7.0, HMTTL : 31.0, HMGP : 3.5, HMGL : A-
    TTLMark : 327.0, Per : 72.67, TTLGPA : 36.0, GPA : 4.0, LG : A



                    HOLY LAND College
                    1st Term Mark Sheet-2021
                   ..........................
    Id: 40 of Clas IX        Obtain postion: 13
    BANCQ : 25.0, BAN20 : 12.0, BanTTL : 37.0, BanGP : 4.0, BanGL : A
    ENGCQ : 28.0, ENG20 : 14.0, EngTTL : 42.0, EngGP : 5.0, EngGL : A+
    MathCQ : 29.0, Math20 : 9.0, MathTTL : 38.0, MathGP : 4.0, MathGL : A
    BGSCQ : 27.0, BGS20 : 17.0, BGSTTL : 44.0, BGSGP : 5.0, BGSGL : A+
    ReliCQ : 29.0, Reli20 : 18.0, ReliTTL : 47.0, ReliGP : 5.0, ReliGL : A+
    PhyCQ : 28.0, Phy20 : 10.0, PhyTTL : 38.0, PhyGP : 4.0, PhyGL : A
    CheCQ : 28.0, Che20 : 16.0, CheTTL : 44.0, CheGP : 5.0, CheGL : A+
    BioCQ : 23.0, Bio20 : 14.0, BioTTL : 37.0, BioGP : 4.0, BioGL : A
    HMCQ : nan, HM20 : 9.0, HMTTL : nan, HMGP : 0.0, HMGL : F
    TTLMark : nan, Per : nan, TTLGPA : 36.0, GPA : 4.0, LG : A



                    HOLY LAND College
                    1st Term Mark Sheet-2021
                   ..........................
    Id: 8 of Clas IX        Obtain postion: 14
    BANCQ : 23.0, BAN20 : 10.0, BanTTL : 33.0, BanGP : 3.5, BanGL : A-
    ENGCQ : 19.0, ENG20 : 6.0, EngTTL : 25.0, EngGP : 3.0, EngGL : B
    MathCQ : 30.0, Math20 : 11.0, MathTTL : 41.0, MathGP : 5.0, MathGL : A+
    BGSCQ : 27.0, BGS20 : 18.0, BGSTTL : 45.0, BGSGP : 5.0, BGSGL : A+
    ReliCQ : 28.0, Reli20 : 17.0, ReliTTL : 45.0, ReliGP : 5.0, ReliGL : A+
    PhyCQ : nan, Phy20 : 14.0, PhyTTL : nan, PhyGP : 0.0, PhyGL : F
    CheCQ : 24.0, Che20 : 18.0, CheTTL : 42.0, CheGP : 5.0, CheGL : A+
    BioCQ : 20.0, Bio20 : 19.0, BioTTL : 39.0, BioGP : 4.0, BioGL : A
    HMCQ : 23.0, HM20 : 12.0, HMTTL : 35.0, HMGP : 4.0, HMGL : A
    TTLMark : nan, Per : nan, TTLGPA : 34.5, GPA : 3.83, LG : A-



                    HOLY LAND College
                    1st Term Mark Sheet-2021
                   ..........................
    Id: 22 of Clas IX        Obtain postion: 15
    BANCQ : 25.0, BAN20 : 13.0, BanTTL : 38.0, BanGP : 4.0, BanGL : A
    ENGCQ : 21.0, ENG20 : 16.0, EngTTL : 37.0, EngGP : 4.0, EngGL : A
    MathCQ : 30.0, Math20 : 14.0, MathTTL : 44.0, MathGP : 5.0, MathGL : A+
    BGSCQ : 22.0, BGS20 : 13.0, BGSTTL : 35.0, BGSGP : 4.0, BGSGL : A
    ReliCQ : 29.0, Reli20 : 13.0, ReliTTL : 42.0, ReliGP : 5.0, ReliGL : A+
    PhyCQ : 30.0, Phy20 : nan, PhyTTL : nan, PhyGP : 0.0, PhyGL : F
    CheCQ : 26.0, Che20 : 7.0, CheTTL : 33.0, CheGP : 3.5, CheGL : A-
    BioCQ : 24.0, Bio20 : 14.0, BioTTL : 38.0, BioGP : 4.0, BioGL : A
    HMCQ : 29.0, HM20 : 11.0, HMTTL : 40.0, HMGP : 5.0, HMGL : A+
    TTLMark : nan, Per : nan, TTLGPA : 34.5, GPA : 3.83, LG : A-



                    HOLY LAND College
                    1st Term Mark Sheet-2021
                   ..........................
    Id: 2 of Clas IX        Obtain postion: 16
    BANCQ : 22.0, BAN20 : 12.0, BanTTL : 34.0, BanGP : 3.5, BanGL : A-
    ENGCQ : 18.0, ENG20 : 10.0, EngTTL : 28.0, EngGP : 3.0, EngGL : B
    MathCQ : 30.0, Math20 : 6.0, MathTTL : 36.0, MathGP : 4.0, MathGL : A
    BGSCQ : 27.0, BGS20 : 8.0, BGSTTL : 35.0, BGSGP : 4.0, BGSGL : A
    ReliCQ : 29.0, Reli20 : 18.0, ReliTTL : 47.0, ReliGP : 5.0, ReliGL : A+
    PhyCQ : 27.0, Phy20 : 10.0, PhyTTL : 37.0, PhyGP : 4.0, PhyGL : A
    CheCQ : 30.0, Che20 : 13.0, CheTTL : 43.0, CheGP : 5.0, CheGL : A+
    BioCQ : 25.0, Bio20 : 16.0, BioTTL : 41.0, BioGP : 5.0, BioGL : A+
    HMCQ : nan, HM20 : nan, HMTTL : nan, HMGP : 0.0, HMGL : F
    TTLMark : nan, Per : nan, TTLGPA : 33.5, GPA : 3.72, LG : A-



                    HOLY LAND College
                    1st Term Mark Sheet-2021
                   ..........................
    Id: 36 of Clas IX        Obtain postion: 17
    BANCQ : 26.0, BAN20 : 8.0, BanTTL : 34.0, BanGP : 3.5, BanGL : A-
    ENGCQ : 19.0, ENG20 : 7.0, EngTTL : 26.0, EngGP : 3.0, EngGL : B
    MathCQ : 28.0, Math20 : 8.0, MathTTL : 36.0, MathGP : 4.0, MathGL : A
    BGSCQ : 27.0, BGS20 : 10.0, BGSTTL : 37.0, BGSGP : 4.0, BGSGL : A
    ReliCQ : 29.0, Reli20 : 15.0, ReliTTL : 44.0, ReliGP : 5.0, ReliGL : A+
    PhyCQ : 30.0, Phy20 : 11.0, PhyTTL : 41.0, PhyGP : 5.0, PhyGL : A+
    CheCQ : nan, Che20 : 10.0, CheTTL : nan, CheGP : 0.0, CheGL : F
    BioCQ : 29.0, Bio20 : 12.0, BioTTL : 41.0, BioGP : 5.0, BioGL : A+
    HMCQ : 28.0, HM20 : 7.0, HMTTL : 35.0, HMGP : 4.0, HMGL : A
    TTLMark : nan, Per : nan, TTLGPA : 33.5, GPA : 3.72, LG : A-



                    HOLY LAND College
                    1st Term Mark Sheet-2021
                   ..........................
    Id: 28 of Clas IX        Obtain postion: 18
    BANCQ : 21.0, BAN20 : 11.0, BanTTL : 32.0, BanGP : 3.5, BanGL : A-
    ENGCQ : 17.0, ENG20 : 10.0, EngTTL : 27.0, EngGP : 3.0, EngGL : B
    MathCQ : 30.0, Math20 : 3.0, MathTTL : 33.0, MathGP : 3.5, MathGL : A-
    BGSCQ : 25.0, BGS20 : 12.0, BGSTTL : 37.0, BGSGP : 4.0, BGSGL : A
    ReliCQ : 24.0, Reli20 : 13.0, ReliTTL : 37.0, ReliGP : 4.0, ReliGL : A
    PhyCQ : 29.0, Phy20 : 8.0, PhyTTL : 37.0, PhyGP : 4.0, PhyGL : A
    CheCQ : 26.0, Che20 : 12.0, CheTTL : 38.0, CheGP : 4.0, CheGL : A
    BioCQ : 19.0, Bio20 : 7.0, BioTTL : 26.0, BioGP : 3.0, BioGL : B
    HMCQ : 25.0, HM20 : 11.0, HMTTL : 36.0, HMGP : 4.0, HMGL : A
    TTLMark : 303.0, Per : 67.33, TTLGPA : 33.0, GPA : 3.67, LG : A-



                    HOLY LAND College
                    1st Term Mark Sheet-2021
                   ..........................
    Id: 16 of Clas IX        Obtain postion: 19
    BANCQ : 22.0, BAN20 : nan, BanTTL : nan, BanGP : 0.0, BanGL : F
    ENGCQ : 21.0, ENG20 : 7.0, EngTTL : 28.0, EngGP : 3.0, EngGL : B
    MathCQ : 30.0, Math20 : 8.0, MathTTL : 38.0, MathGP : 4.0, MathGL : A
    BGSCQ : 20.0, BGS20 : 17.0, BGSTTL : 37.0, BGSGP : 4.0, BGSGL : A
    ReliCQ : 29.0, Reli20 : 12.0, ReliTTL : 41.0, ReliGP : 5.0, ReliGL : A+
    PhyCQ : 27.0, Phy20 : 9.0, PhyTTL : 36.0, PhyGP : 4.0, PhyGL : A
    CheCQ : 18.0, Che20 : 13.0, CheTTL : 31.0, CheGP : 3.5, CheGL : A-
    BioCQ : 27.0, Bio20 : 14.0, BioTTL : 41.0, BioGP : 5.0, BioGL : A+
    HMCQ : 26.0, HM20 : 9.0, HMTTL : 35.0, HMGP : 4.0, HMGL : A
    TTLMark : nan, Per : nan, TTLGPA : 32.5, GPA : 3.61, LG : A-



                    HOLY LAND College
                    1st Term Mark Sheet-2021
                   ..........................
    Id: 27 of Clas IX        Obtain postion: 20
    BANCQ : 23.0, BAN20 : 18.0, BanTTL : 41.0, BanGP : 5.0, BanGL : A+
    ENGCQ : 22.0, ENG20 : 16.0, EngTTL : 38.0, EngGP : 4.0, EngGL : A
    MathCQ : 19.0, Math20 : 16.0, MathTTL : 35.0, MathGP : 4.0, MathGL : A
    BGSCQ : 20.0, BGS20 : 18.0, BGSTTL : 38.0, BGSGP : 4.0, BGSGL : A
    ReliCQ : nan, Reli20 : 17.0, ReliTTL : nan, ReliGP : 0.0, ReliGL : F
    PhyCQ : 15.0, Phy20 : 10.0, PhyTTL : 25.0, PhyGP : 3.0, PhyGL : B
    CheCQ : 26.0, Che20 : 19.0, CheTTL : 45.0, CheGP : 5.0, CheGL : A+
    BioCQ : 15.0, Bio20 : 17.0, BioTTL : 32.0, BioGP : 3.5, BioGL : A-
    HMCQ : 24.0, HM20 : 14.0, HMTTL : 38.0, HMGP : 4.0, HMGL : A
    TTLMark : nan, Per : nan, TTLGPA : 32.5, GPA : 3.61, LG : A-



                    HOLY LAND College
                    1st Term Mark Sheet-2021
                   ..........................
    Id: 13 of Clas IX        Obtain postion: 21
    BANCQ : 23.0, BAN20 : 13.0, BanTTL : 36.0, BanGP : 4.0, BanGL : A
    ENGCQ : 22.0, ENG20 : 17.0, EngTTL : 39.0, EngGP : 4.0, EngGL : A
    MathCQ : 29.0, Math20 : 18.0, MathTTL : 47.0, MathGP : 5.0, MathGL : A+
    BGSCQ : 23.0, BGS20 : 11.0, BGSTTL : 34.0, BGSGP : 3.5, BGSGL : A-
    ReliCQ : nan, Reli20 : 13.0, ReliTTL : nan, ReliGP : 0.0, ReliGL : F
    PhyCQ : 30.0, Phy20 : 13.0, PhyTTL : 43.0, PhyGP : 5.0, PhyGL : A+
    CheCQ : 25.0, Che20 : nan, CheTTL : nan, CheGP : 0.0, CheGL : F
    BioCQ : 25.0, Bio20 : 18.0, BioTTL : 43.0, BioGP : 5.0, BioGL : A+
    HMCQ : 24.0, HM20 : 14.0, HMTTL : 38.0, HMGP : 4.0, HMGL : A
    TTLMark : nan, Per : nan, TTLGPA : 30.5, GPA : 3.39, LG : B



                    HOLY LAND College
                    1st Term Mark Sheet-2021
                   ..........................
    Id: 15 of Clas IX        Obtain postion: 22
    BANCQ : 24.0, BAN20 : 14.0, BanTTL : 38.0, BanGP : 4.0, BanGL : A
    ENGCQ : 17.0, ENG20 : 9.0, EngTTL : 26.0, EngGP : 3.0, EngGL : B
    MathCQ : 27.0, Math20 : 10.0, MathTTL : 37.0, MathGP : 4.0, MathGL : A
    BGSCQ : 23.0, BGS20 : 13.0, BGSTTL : 36.0, BGSGP : 4.0, BGSGL : A
    ReliCQ : 29.0, Reli20 : 12.0, ReliTTL : 41.0, ReliGP : 5.0, ReliGL : A+
    PhyCQ : 12.0, Phy20 : 7.0, PhyTTL : 19.0, PhyGP : 0.0, PhyGL : F
    CheCQ : 13.0, Che20 : 12.0, CheTTL : 25.0, CheGP : 3.0, CheGL : B
    BioCQ : 21.0, Bio20 : 12.0, BioTTL : 33.0, BioGP : 3.5, BioGL : A-
    HMCQ : 25.0, HM20 : 6.0, HMTTL : 31.0, HMGP : 3.5, HMGL : A-
    TTLMark : 286.0, Per : 63.56, TTLGPA : 30.0, GPA : 3.33, LG : B



                    HOLY LAND College
                    1st Term Mark Sheet-2021
                   ..........................
    Id: 18 of Clas IX        Obtain postion: 23
    BANCQ : 21.0, BAN20 : 8.0, BanTTL : 29.0, BanGP : 3.0, BanGL : B
    ENGCQ : 25.0, ENG20 : 7.0, EngTTL : 32.0, EngGP : 3.5, EngGL : A-
    MathCQ : 25.0, Math20 : 7.0, MathTTL : 32.0, MathGP : 3.5, MathGL : A-
    BGSCQ : 17.0, BGS20 : 11.0, BGSTTL : 28.0, BGSGP : 3.0, BGSGL : B
    ReliCQ : 28.0, Reli20 : 9.0, ReliTTL : 37.0, ReliGP : 4.0, ReliGL : A

In [26]:
# Create Message
for (row, rowseries) in df.iterrows():
    #print(row)
    #print(rowseries)
    message = ''' 
                    HOLY LAND College
                    1st Term Mark Sheet-2021
                   .......................... 
    Id: {} of Clas IX        Obtain postion: {}
    ..............................................
    Sub   CQ    |  MCQ    |  TTL    |  GP   |  LG
    ..............................................
    Ban   {}  |  {}   |  {}   |  {}  |  {}
    Eng   {}  |  {}   |  {}   |  {}  |  {}
    Math  {}  |  {}   |  {}   |  {}  |  {}
    BGS   {}  |  {}   |  {}   |  {}  |  {}
    Reli  {}  |  {}   |  {}   |  {}  |  {}
    Phy   {}  |  {}   |  {}   |  {}  |  {}
    Che   {}  |  {}   |  {}   |  {}  |  {}
    Bio   {}  |  {}   |  {}   |  {}  |  {}
    HM    {}  |  {}   |  {}   |  {}  |  {}
    {} : {}, {} : {}, {} : {}, {} : {}  
            
    '''.format(rowseries[0], rowseries[51],
              rowseries[1],
              rowseries[2],  
               rowseries[3], 
               rowseries[4], 
               rowseries[5],
               rowseries[6],
               rowseries[7],  
               rowseries[8], 
               rowseries[9], 
               rowseries[10],
               rowseries[11],
               rowseries[12],  
               rowseries[13], 
               rowseries[14], 
               rowseries[15],
               rowseries[16],
               rowseries[17],  
               rowseries[18], 
               rowseries[19], 
               rowseries[20],
               rowseries[21],
              rowseries[22],  
               rowseries[23], 
               rowseries[24], 
               rowseries[25],
               rowseries[26],
               rowseries[27],  
               rowseries[28], 
               rowseries[29], 
               rowseries[30],
               rowseries[31],
              rowseries[32],  
               rowseries[33], 
               rowseries[34], 
               rowseries[35],
               rowseries[36],
               rowseries[37],  
               rowseries[38], 
               rowseries[39], 
               rowseries[40],
               rowseries[41],
               rowseries[42],  
               rowseries[43], 
               rowseries[44], 
               rowseries[45],
               rowseries.index[46],rowseries[46],
               rowseries.index[47],rowseries[47],  
               rowseries.index[49],rowseries[49], 
               rowseries.index[50],rowseries[50])
    print(message)

                    HOLY LAND College
                    1st Term Mark Sheet-2021
                   ..........................
    Id: 43 of Clas IX        Obtain postion: 1
    ..............................................
    Sub   CQ    |  MCQ    |  TTL    |  GP   |  LG
    ..............................................
    Ban   24.0  |  16.0   |  40.0   |  5.0  |  A+
    Eng   22.0  |  19.0   |  41.0   |  5.0  |  A+
    Math  24.0  |  14.0   |  38.0   |  4.0  |  A
    BGS   27.0  |  17.0   |  44.0   |  5.0  |  A+
    Reli  29.0  |  17.0   |  46.0   |  5.0  |  A+
    Phy   27.0  |  13.0   |  40.0   |  5.0  |  A+
    Che   28.0  |  18.0   |  46.0   |  5.0  |  A+
    Bio   23.0  |  20.0   |  43.0   |  5.0  |  A+
    HM    24.0  |  19.0   |  43.0   |  5.0  |  A+
    TTLMark : 381.0, Per : 84.67, GPA : 4.89, LG : A



                    HOLY LAND College
                    1st Term Mark Sheet-2021
                   ..........................
    Id: 7 of Clas IX        Obtain postion: 2
    ..............................................
    Sub   CQ    |  MCQ    |  TTL    |  GP   |  LG
    ..............................................
    Ban   25.0  |  13.0   |  38.0   |  4.0  |  A
    Eng   25.0  |  15.0   |  40.0   |  5.0  |  A+
    Math  30.0  |  17.0   |  47.0   |  5.0  |  A+
    BGS   26.0  |  10.0   |  36.0   |  4.0  |  A
    Reli  29.0  |  16.0   |  45.0   |  5.0  |  A+
    Phy   30.0  |  14.0   |  44.0   |  5.0  |  A+
    Che   28.0  |  16.0   |  44.0   |  5.0  |  A+
    Bio   30.0  |  16.0   |  46.0   |  5.0  |  A+
    HM    28.0  |  18.0   |  46.0   |  5.0  |  A+
    TTLMark : 386.0, Per : 85.78, GPA : 4.78, LG : A



                    HOLY LAND College
                    1st Term Mark Sheet-2021
                   ..........................
    Id: 17 of Clas IX        Obtain postion: 3
    ..............................................
    Sub   CQ    |  MCQ    |  TTL    |  GP   |  LG
    ..............................................
    Ban   25.0  |  15.0   |  40.0   |  5.0  |  A+
    Eng   17.0  |  12.0   |  29.0   |  3.0  |  B
    Math  30.0  |  15.0   |  45.0   |  5.0  |  A+
    BGS   27.0  |  15.0   |  42.0   |  5.0  |  A+
    Reli  28.0  |  17.0   |  45.0   |  5.0  |  A+
    Phy   30.0  |  15.0   |  45.0   |  5.0  |  A+
    Che   28.0  |  20.0   |  48.0   |  5.0  |  A+
    Bio   28.0  |  18.0   |  46.0   |  5.0  |  A+
    HM    28.0  |  15.0   |  43.0   |  5.0  |  A+
    TTLMark : 383.0, Per : 85.11, GPA : 4.78, LG : A



                    HOLY LAND College
                    1st Term Mark Sheet-2021
                   ..........................
    Id: 6 of Clas IX        Obtain postion: 4
    ..............................................
    Sub   CQ    |  MCQ    |  TTL    |  GP   |  LG
    ..............................................
    Ban   25.0  |  16.0   |  41.0   |  5.0  |  A+
    Eng   20.0  |  15.0   |  35.0   |  4.0  |  A
    Math  30.0  |  17.0   |  47.0   |  5.0  |  A+
    BGS   24.0  |  15.0   |  39.0   |  4.0  |  A
    Reli  29.0  |  17.0   |  46.0   |  5.0  |  A+
    Phy   29.0  |  14.0   |  43.0   |  5.0  |  A+
    Che   29.0  |  15.0   |  44.0   |  5.0  |  A+
    Bio   24.0  |  18.0   |  42.0   |  5.0  |  A+
    HM    30.0  |  15.0   |  45.0   |  5.0  |  A+
    TTLMark : 382.0, Per : 84.89, GPA : 4.78, LG : A



                    HOLY LAND College
                    1st Term Mark Sheet-2021
                   ..........................
    Id: 1 of Clas IX        Obtain postion: 5
    ..............................................
    Sub   CQ    |  MCQ    |  TTL    |  GP   |  LG
    ..............................................
    Ban   23.0  |  16.0   |  39.0   |  4.0  |  A
    Eng   20.0  |  19.0   |  39.0   |  4.0  |  A
    Math  30.0  |  18.0   |  48.0   |  5.0  |  A+
    BGS   27.0  |  18.0   |  45.0   |  5.0  |  A+
    Reli  29.0  |  20.0   |  49.0   |  5.0  |  A+
    Phy   24.0  |  11.0   |  35.0   |  4.0  |  A
    Che   22.0  |  19.0   |  41.0   |  5.0  |  A+
    Bio   26.0  |  18.0   |  44.0   |  5.0  |  A+
    HM    28.0  |  15.0   |  43.0   |  5.0  |  A+
    TTLMark : 383.0, Per : 85.11, GPA : 4.67, LG : A



                    HOLY LAND College
                    1st Term Mark Sheet-2021
                   ..........................
    Id: 26 of Clas IX        Obtain postion: 6
    ..............................................
    Sub   CQ    |  MCQ    |  TTL    |  GP   |  LG
    ..............................................
    Ban   20.0  |  13.0   |  33.0   |  3.5  |  A-
    Eng   19.0  |  15.0   |  34.0   |  3.5  |  A-
    Math  30.0  |  19.0   |  49.0   |  5.0  |  A+
    BGS   24.0  |  17.0   |  41.0   |  5.0  |  A+
    Reli  29.0  |  14.0   |  43.0   |  5.0  |  A+
    Phy   28.0  |  17.0   |  45.0   |  5.0  |  A+
    Che   28.0  |  17.0   |  45.0   |  5.0  |  A+
    Bio   24.0  |  19.0   |  43.0   |  5.0  |  A+
    HM    28.0  |  19.0   |  47.0   |  5.0  |  A+
    TTLMark : 380.0, Per : 84.44, GPA : 4.67, LG : A



                    HOLY LAND College
                    1st Term Mark Sheet-2021
                   ..........................
    Id: 5 of Clas IX        Obtain postion: 7
    ..............................................
    Sub   CQ    |  MCQ    |  TTL    |  GP   |  LG
    ..............................................
    Ban   24.0  |  17.0   |  41.0   |  5.0  |  A+
    Eng   26.0  |  13.0   |  39.0   |  4.0  |  A
    Math  29.0  |  14.0   |  43.0   |  5.0  |  A+
    BGS   22.0  |  16.0   |  38.0   |  4.0  |  A
    Reli  29.0  |  18.0   |  47.0   |  5.0  |  A+
    Phy   27.0  |  9.0   |  36.0   |  4.0  |  A
    Che   29.0  |  18.0   |  47.0   |  5.0  |  A+
    Bio   25.0  |  16.0   |  41.0   |  5.0  |  A+
    HM    28.0  |  16.0   |  44.0   |  5.0  |  A+
    TTLMark : 376.0, Per : 83.56, GPA : 4.67, LG : A



                    HOLY LAND College
                    1st Term Mark Sheet-2021
                   ..........................
    Id: 12 of Clas IX        Obtain postion: 8
    ..............................................
    Sub   CQ    |  MCQ    |  TTL    |  GP   |  LG
    ..............................................
    Ban   25.0  |  11.0   |  36.0   |  4.0  |  A
    Eng   27.0  |  14.0   |  41.0   |  5.0  |  A+
    Math  30.0  |  9.0   |  39.0   |  4.0  |  A
    BGS   27.0  |  11.0   |  38.0   |  4.0  |  A
    Reli  29.0  |  16.0   |  45.0   |  5.0  |  A+
    Phy   26.0  |  11.0   |  37.0   |  4.0  |  A
    Che   28.0  |  16.0   |  44.0   |  5.0  |  A+
    Bio   27.0  |  14.0   |  41.0   |  5.0  |  A+
    HM    29.0  |  9.0   |  38.0   |  4.0  |  A
    TTLMark : 359.0, Per : 79.78, GPA : 4.44, LG : A



                    HOLY LAND College
                    1st Term Mark Sheet-2021
                   ..........................
    Id: 24 of Clas IX        Obtain postion: 9
    ..............................................
    Sub   CQ    |  MCQ    |  TTL    |  GP   |  LG
    ..............................................
    Ban   20.0  |  15.0   |  35.0   |  4.0  |  A
    Eng   20.0  |  17.0   |  37.0   |  4.0  |  A
    Math  24.0  |  18.0   |  42.0   |  5.0  |  A+
    BGS   17.0  |  15.0   |  32.0   |  3.5  |  A-
    Reli  28.0  |  15.0   |  43.0   |  5.0  |  A+
    Phy   25.0  |  13.0   |  38.0   |  4.0  |  A
    Che   25.0  |  19.0   |  44.0   |  5.0  |  A+
    Bio   22.0  |  15.0   |  37.0   |  4.0  |  A
    HM    28.0  |  13.0   |  41.0   |  5.0  |  A+
    TTLMark : 349.0, Per : 77.56, GPA : 4.39, LG : A



                    HOLY LAND College
                    1st Term Mark Sheet-2021
                   ..........................
    Id: 14 of Clas IX        Obtain postion: 10
    ..............................................
    Sub   CQ    |  MCQ    |  TTL    |  GP   |  LG
    ..............................................
    Ban   24.0  |  14.0   |  38.0   |  4.0  |  A
    Eng   18.0  |  13.0   |  31.0   |  3.5  |  A-
    Math  30.0  |  10.0   |  40.0   |  5.0  |  A+
    BGS   25.0  |  15.0   |  40.0   |  5.0  |  A+
    Reli  26.0  |  17.0   |  43.0   |  5.0  |  A+
    Phy   24.0  |  8.0   |  32.0   |  3.5  |  A-
    Che   26.0  |  15.0   |  41.0   |  5.0  |  A+
    Bio   28.0  |  12.0   |  40.0   |  5.0  |  A+
    HM    21.0  |  13.0   |  34.0   |  3.5  |  A-
    TTLMark : 339.0, Per : 75.33, GPA : 4.39, LG : A



                    HOLY LAND College
                    1st Term Mark Sheet-2021
                   ..........................
    Id: 31 of Clas IX        Obtain postion: 11
    ..............................................
    Sub   CQ    |  MCQ    |  TTL    |  GP   |  LG
    ..............................................
    Ban   18.0  |  16.0   |  34.0   |  3.5  |  A-
    Eng   15.0  |  10.0   |  25.0   |  3.0  |  B
    Math  26.0  |  5.0   |  31.0   |  3.5  |  A-
    BGS   26.0  |  16.0   |  42.0   |  5.0  |  A+
    Reli  29.0  |  18.0   |  47.0   |  5.0  |  A+
    Phy   27.0  |  11.0   |  38.0   |  4.0  |  A
    Che   26.0  |  17.0   |  43.0   |  5.0  |  A+
    Bio   22.0  |  16.0   |  38.0   |  4.0  |  A
    HM    30.0  |  18.0   |  48.0   |  5.0  |  A+
    TTLMark : 346.0, Per : 76.89, GPA : 4.22, LG : A



                    HOLY LAND College
                    1st Term Mark Sheet-2021
                   ..........................
    Id: 44 of Clas IX        Obtain postion: 12
    ..............................................
    Sub   CQ    |  MCQ    |  TTL    |  GP   |  LG
    ..............................................
    Ban   23.0  |  15.0   |  38.0   |  4.0  |  A
    Eng   24.0  |  14.0   |  38.0   |  4.0  |  A
    Math  24.0  |  8.0   |  32.0   |  3.5  |  A-
    BGS   24.0  |  12.0   |  36.0   |  4.0  |  A
    Reli  29.0  |  15.0   |  44.0   |  5.0  |  A+
    Phy   28.0  |  6.0   |  34.0   |  3.5  |  A-
    Che   25.0  |  15.0   |  40.0   |  5.0  |  A+
    Bio   18.0  |  16.0   |  34.0   |  3.5  |  A-
    HM    24.0  |  7.0   |  31.0   |  3.5  |  A-
    TTLMark : 327.0, Per : 72.67, GPA : 4.0, LG : A



                    HOLY LAND College
                    1st Term Mark Sheet-2021
                   ..........................
    Id: 40 of Clas IX        Obtain postion: 13
    ..............................................
    Sub   CQ    |  MCQ    |  TTL    |  GP   |  LG
    ..............................................
    Ban   25.0  |  12.0   |  37.0   |  4.0  |  A
    Eng   28.0  |  14.0   |  42.0   |  5.0  |  A+
    Math  29.0  |  9.0   |  38.0   |  4.0  |  A
    BGS   27.0  |  17.0   |  44.0   |  5.0  |  A+
    Reli  29.0  |  18.0   |  47.0   |  5.0  |  A+
    Phy   28.0  |  10.0   |  38.0   |  4.0  |  A
    Che   28.0  |  16.0   |  44.0   |  5.0  |  A+
    Bio   23.0  |  14.0   |  37.0   |  4.0  |  A
    HM    nan  |  9.0   |  nan   |  0.0  |  F
    TTLMark : nan, Per : nan, GPA : 4.0, LG : A



                    HOLY LAND College
                    1st Term Mark Sheet-2021
                   ..........................
    Id: 8 of Clas IX        Obtain postion: 14
    ..............................................
    Sub   CQ    |  MCQ    |  TTL    |  GP   |  LG
    ..............................................
    Ban   23.0  |  10.0   |  33.0   |  3.5  |  A-
    Eng   19.0  |  6.0   |  25.0   |  3.0  |  B
    Math  30.0  |  11.0   |  41.0   |  5.0  |  A+
    BGS   27.0  |  18.0   |  45.0   |  5.0  |  A+
    Reli  28.0  |  17.0   |  45.0   |  5.0  |  A+
    Phy   nan  |  14.0   |  nan   |  0.0  |  F
    Che   24.0  |  18.0   |  42.0   |  5.0  |  A+
    Bio   20.0  |  19.0   |  39.0   |  4.0  |  A
    HM    23.0  |  12.0   |  35.0   |  4.0  |  A
    TTLMark : nan, Per : nan, GPA : 3.83, LG : A-



                    HOLY LAND College
                    1st Term Mark Sheet-2021
                   ..........................
    Id: 22 of Clas IX        Obtain postion: 15
    ..............................................
    Sub   CQ    |  MCQ    |  TTL    |  GP   |  LG
    ..............................................
    Ban   25.0  |  13.0   |  38.0   |  4.0  |  A
    Eng   21.0  |  16.0   |  37.0   |  4.0  |  A
    Math  30.0  |  14.0   |  44.0   |  5.0  |  A+
    BGS   22.0  |  13.0   |  35.0   |  4.0  |  A
    Reli  29.0  |  13.0   |  42.0   |  5.0  |  A+
    Phy   30.0  |  nan   |  nan   |  0.0  |  F
    Che   26.0  |  7.0   |  33.0   |  3.5  |  A-
    Bio   24.0  |  14.0   |  38.0   |  4.0  |  A
    HM    29.0  |  11.0   |  40.0   |  5.0  |  A+
    TTLMark : nan, Per : nan, GPA : 3.83, LG : A-



                    HOLY LAND College
                    1st Term Mark Sheet-2021
                   ..........................
    Id: 2 of Clas IX        Obtain postion: 16
    ..............................................
    Sub   CQ    |  MCQ    |  TTL    |  GP   |  LG
    ..............................................
    Ban   22.0  |  12.0   |  34.0   |  3.5  |  A-
    Eng   18.0  |  10.0   |  28.0   |  3.0  |  B
    Math  30.0  |  6.0   |  36.0   |  4.0  |  A
    BGS   27.0  |  8.0   |  35.0   |  4.0  |  A
    Reli  29.0  |  18.0   |  47.0   |  5.0  |  A+
    Phy   27.0  |  10.0   |  37.0   |  4.0  |  A
    Che   30.0  |  13.0   |  43.0   |  5.0  |  A+
    Bio   25.0  |  16.0   |  41.0   |  5.0  |  A+
    HM    nan  |  nan   |  nan   |  0.0  |  F
    TTLMark : nan, Per : nan, GPA : 3.72, LG : A-



                    HOLY LAND College
                    1st Term Mark Sheet-2021
                   ..........................
    Id: 36 of Clas IX        Obtain postion: 17
    ..............................................
    Sub   CQ    |  MCQ    |  TTL    |  GP   |  LG
    ..............................................
    Ban   26.0  |  8.0   |  34.0   |  3.5  |  A-
    Eng   19.0  |  7.0   |  26.0   |  3.0  |  B
    Math  28.0  |  8.0   |  36.0   |  4.0  |  A
    BGS   27.0  |  10.0   |  37.0   |  4.0  |  A
    Reli  29.0  |  15.0   |  44.0   |  5.0  |  A+
    Phy   30.0  |  11.0   |  41.0   |  5.0  |  A+
    Che   nan  |  10.0   |  nan   |  0.0  |  F
    Bio   29.0  |  12.0   |  41.0   |  5.0  |  A+
    HM    28.0  |  7.0   |  35.0   |  4.0  |  A
    TTLMark : nan, Per : nan, GPA : 3.72, LG : A-



                    HOLY LAND College
                    1st Term Mark Sheet-2021
                   ..........................
    Id: 28 of Clas IX        Obtain postion: 18
    ..............................................
    Sub   CQ    |  MCQ    |  TTL    |  GP   |  LG
    ..............................................
    Ban   21.0  |  11.0   |  32.0   |  3.5  |  A-
    Eng   17.0  |  10.0   |  27.0   |  3.0  |  B
    Math  30.0  |  3.0   |  33.0   |  3.5  |  A-
    BGS   25.0  |  12.0   |  37.0   |  4.0  |  A
    Reli  24.0  |  13.0   |  37.0   |  4.0  |  A
    Phy   29.0  |  8.0   |  37.0   |  4.0  |  A
    Che   26.0  |  12.0   |  38.0   |  4.0  |  A
    Bio   19.0  |  7.0   |  26.0   |  3.0  |  B
    HM    25.0  |  11.0   |  36.0   |  4.0  |  A
    TTLMark : 303.0, Per : 67.33, GPA : 3.67, LG : A-



                    HOLY LAND College
                    1st Term Mark Sheet-2021
                   ..........................
    Id: 16 of Clas IX        Obtain postion: 19
    ..............................................
    Sub   CQ    |  MCQ    |  TTL    |  GP   |  LG
    ..............................................
    Ban   22.0  |  nan   |  nan   |  0.0  |  F
    Eng   21.0  |  7.0   |  28.0   |  3.0  |  B
    Math  30.0  |  8.0   |  38.0   |  4.0  |  A
    BGS   20.0  |  17.0   |  37.0   |  4.0  |  A
    Reli  29.0  |  12.0   |  41.0   |  5.0  |  A+
    Phy   27.0  |  9.0   |  36.0   |  4.0  |  A
    Che   18.0  |  13.0   |  31.0   |  3.5  |  A-
    Bio   27.0  |  14.0   |  41.0   |  5.0  |  A+
    HM    26.0  |  9.0   |  35.0   |  4.0  |  A
    TTLMark : nan, Per : nan, GPA : 3.61, LG : A-



                    HOLY LAND College
                    1st Term Mark Sheet-2021
                   ..........................
    Id: 27 of Clas IX        Obtain postion: 20
    ..............................................
    Sub   CQ    |  MCQ    |  TTL    |  GP   |  LG
    ..............................................
    Ban   23.0  |  18.0   |  41.0   |  5.0  |  A+
    Eng   22.0  |  16.0   |  38.0   |  4.0  |  A
    Math  19.0  |  16.0   |  35.0   |  4.0  |  A
    BGS   20.0  |  18.0   |  38.0   |  4.0  |  A
    Reli  nan  |  17.0   |  nan   |  0.0  |  F
    Phy   15.0  |  10.0   |  25.0   |  3.0  |  B
    Che   26.0  |  19.0   |  45.0   |  5.0  |  A+
    Bio   15.0  |  17.0   |  32.0   |  3.5  |  A-
    HM    24.0  |  14.0   |  38.0   |  4.0  |  A
    TTLMark : nan, Per : nan, GPA : 3.61, LG : A-



                    HOLY LAND College
                    1st Term Mark Sheet-2021
                   ..........................
    Id: 13 of Clas IX        Obtain postion: 21
    ..............................................
    Sub   CQ    |  MCQ    |  TTL    |  GP   |  LG
    ..............................................
    Ban   23.0  |  13.0   |  36.0   |  4.0  |  A
    Eng   22.0  |  17.0   |  39.0   |  4.0  |  A
    Math  29.0  |  18.0   |  47.0   |  5.0  |  A+
    BGS   23.0  |  11.0   |  34.0   |  3.5  |  A-
    Reli  nan  |  13.0   |  nan   |  0.0  |  F
    Phy   30.0  |  13.0   |  43.0   |  5.0  |  A+
    Che   25.0  |  nan   |  nan   |  0.0  |  F
    Bio   25.0  |  18.0   |  43.0   |  5.0  |  A+
    HM    24.0  |  14.0   |  38.0   |  4.0  |  A
    TTLMark : nan, Per : nan, GPA : 3.39, LG : B



                    HOLY LAND College
                    1st Term Mark Sheet-2021
                   ..........................
    Id: 15 of Clas IX        Obtain postion: 22
    ..............................................
    Sub   CQ    |  MCQ    |  TTL    |  GP   |  LG
    ..............................................
    Ban   24.0  |  14.0   |  38.0   |  4.0  |  A
    Eng   17.0  |  9.0   |  26.0   |  3.0  |  B
    Math  27.0  |  10.0   |  37.0   |  4.0  |  A
    BGS   23.0  |  13.0   |  36.0   |  4.0  |  A
    Reli  29.0  |  12.0   |  41.0   |  5.0  |  A+
    Phy   12.0  |  7.0   |  19.0   |  0.0  |  F
    Che   13.0  |  12.0   |  25.0   |  3.0  |  B
    Bio   21.0  |  12.0   |  33.0   |  3.5  |  A-
    HM    25.0  |  6.0   |  31.0   |  3.5  |  A-
    TTLMark : 286.0, Per : 63.56, GPA : 3.33, LG : B



                    HOLY LAND College
                    1st Term Mark Sheet-2021
                   ..........................
    Id: 18 of Clas IX        Obtain postion: 23
    ..............................................
    Sub   CQ    |  MCQ    |  TTL    |  GP   |  LG
    ..............................................
    Ban   21.0  |  8.0   |  29.0   |  3.0  |  B
    Eng   25.0  |  7.0   |  32.0   |  3.5  |  A-
    Math  25.0  |  7.0   |  32.0   |  3.5  |  A-
    BGS   17.0  |  11.0   |  28.0   |  3.0  |  B
    Reli  28.0  |  9.0   |  37.0   |  4.0  |  A
    Phy   17.0  |  3.0   |  20.0   |  2.0  |  C
    Che   23.0  |  10.0   |  33.0   |  3.5  |  A-
    Bio   26.0  |  4.0   |  30.0   |  3.5  |  A-
    HM    27.0  |  9.0   |  36.0   |  4.0  |  A
    TTLMark : 277.0, Per : 61.56, GPA : 3.33, LG : B



                    HOLY LAND College
                    1st Term Mark Sheet-2021
                   ..........................
    Id: 10 of Clas IX        Obtain postion: 24
    ..............................................
    Sub   CQ    |  MCQ    |  TTL    |  GP   |  LG
    ..............................................
    Ban   20.0  |  12.0   |  32.0   |  3.5  |  A-
    Eng   15.0  |  10.0   |  25.0   |  3.0  |  B
    Math  20.0  |  11.0   |  31.0   |  3.5  |  A-
    BGS   25.0  |  15.0   |  40.0   |  5.0  |  A+
    Reli  26.0  |  16.0   |  42.0   |  5.0  |  A+
    Phy   8.0  |  7.0   |  15.0   |  0.0  |  F
    Che   17.0  |  9.0   |  26.0   |  3.0  |  B
    Bio   20.0  |  9.0   |  29.0   |  3.0  |  B
    HM    19.0  |  9.0   |  28.0   |  3.0  |  B
    TTLMark : 268.0, Per : 59.56, GPA : 3.22, LG : B



                    HOLY LAND College
                    1st Term Mark Sheet-2021
                   ..........................

In [5]:
print('message')

message

In [24]:
from tabulate import tabulate

ModuleNotFoundError: No module named 'tabulate'

In [26]:
df['LG'] =np.where(df['GPA']>=5, 'A+', np.where(df['GPA']>=4, 'A',np.where(df['GPA']>=3.5, 'A-',np.where(df['GPA']>=3, 'B', np.where(df['GPA']>=2, 'C','F')))))

In [27]:
df.to_csv("IXResul.csv")

In [12]:
df['GPA']=if(or(df['BANGP'],df['ENGGP'],df['MathGP'],df['BGSGP'],df['ReliGP'],df['PhyGP'],df['CheGP'],df['BioGP'],df['HMGP'])==0,0,df['GPGPA']/9)

SyntaxError: invalid syntax (<ipython-input-12-105b99ddf0eb>, line 1)

In [14]:
df['xx']=if((df['BANGP']==0|df['ENGGP']==0|df['MathGP']==0|df['BGSGP']==0|df['ReliGP']==0|df['PhyGP']==0|df['CheGP']==0|df['BioGP']==0|df['HMGP']==0),0,df['GPGPA']/9)

SyntaxError: invalid syntax (<ipython-input-14-0ba07966162b>, line 1)

In [5]:
df['ICTGP'] =np.where(2*df['ICT25']>39, 5, np.where(2*df['ICT25']>34, 4,np.where(2*df['ICT25']>29, 3.5,np.where(2*df['ICT25']>24, 3, np.where(2*df['ICT25']>19, 2,0)))))
df['ICTGL'] =np.where(df['ICTGP']==5, 'A+', np.where(df['ICTGP']==4, 'A',np.where(df['ICTGP']==3.5, 'A-',np.where(df['ICTGP']==3, 'B', np.where(df['ICTGP']==2, 'C','F')))))