In [3]:
import pandas as pd

In [4]:
col = pd.read_csv('college.csv')

In [9]:
hos = pd.read_csv('Hostel.csv')
hos.head()

,Id,Name,Group,Gmob,H_Name,H_Rent,Adm_Dt,Lea_dt,H_Dues,H_Afees,...,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69,Unnamed: 70,Unnamed: 71,Unnamed: 72
0,2200004,�mq` �nv�mb,Sci,1.738174e+09,we-2,"6,800",NaN,NaN,"16,320","4,000",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2200007,AvivdvZ �nv�mb,Sci,1.746447e+09,we-1,"7,200",NaN,NaN,"10,800","4,000",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2200008,AvwZK iv�k` Luvb,Sci,1.712702e+09,we-1,"6,800",NaN,NaN,-,"4,000",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2200009,�gvt nvexe kvnvixqvi �`q,Sci,1.722939e+09,we-1,"7,200",NaN,NaN,-,"4,000",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2200015,�gvt dvwng kvnvixi �mvnvb,Sci,1.740845e+09,we-2,"7,200",NaN,NaN,"17,280","4,000",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
comb = pd.merge(col, hos, how = 'outer')

MergeError: No common columns to perform merge on. Merge options: left_on=None, right_on=None, left_index=False, right_index=False

In [8]:
comb = pd.merge(col, hos, how = 'outer')

MergeError: No common columns to perform merge on. Merge options: left_on=None, right_on=None, left_index=False, right_index=False