In [4]:
import pandas as pd

In [20]:
df =pd.read_csv('HSC_Ban_01S.csv', usecols=['Name', 'Points Earned'])
print(df)

             Name  Points Earned
0    01190002SASA           23.0
1    01190003EXAM           25.0
2    01190004HLCR           20.0
3    01190008MIRA           19.0
4    01190010HLCN           15.0
..            ...            ...
151  02190021Exam           19.0
152  02190022HLCT           15.0
153  02190025anna           14.0
154  02190026Babu           19.0
155  02190033J@nu           19.0

[156 rows x 2 columns]

In [12]:
df = pd.read_csv('file.csv', usecols=['column_name'])

In [23]:
df=df.rename(columns={'Points Earned': 'Ban1st'})
df.head()

           Name  Ban1st
0  01190002SASA    23.0
1  01190003EXAM    25.0
2  01190004HLCR    20.0
3  01190008MIRA    19.0
4  01190010HLCN    15.0

In [24]:
df.to_csv('Ban1stSc.csv', index=False)

In [21]:
df = df.set_axis(['Name', 'X', 'Y', 'Z', 'P', 'Ban1st'], axis=1, inplace=False)

             Name  Points Earned
0    01190002SASA           23.0
1    01190003EXAM           25.0
2    01190004HLCR           20.0
3    01190008MIRA           19.0
4    01190010HLCN           15.0
..            ...            ...
151  02190021Exam           19.0
152  02190022HLCT           15.0
153  02190025anna           14.0
154  02190026Babu           19.0
155  02190033J@nu           19.0

[156 rows x 2 columns]

In [14]:
df = df.set_axis(['Name', 'X', 'Y', 'Z', 'P', 'Ban1st'], axis=1, inplace=False)
df

ValueError: Length mismatch: Expected axis has 37 elements, new values have 6 elements

In [18]:
df_copy = df.copy()
df_copy.rename(columns={'Points Earned': 'Ban1st'})
df_copy.head()

,Name,Start Datetime,End Datetime,Time,Percent,Points Earned,Points Possible,‘লালসালু’ কী ধরণের উপন্যাস?,কোন ঘটনায় অনুপমের মন পুলকের আবেশে ভরে যায়?,‘আমার পথ’ প্রবন্ধে কিসের চেয়ে অহংকার ভাল?,...,উদ্দীপকটি পড় এবং প্রশ্নটির উত্তর দাও: ‘কালো আর ধলো ভিতরে সবারই সমান রাঙা’ সাম্যবাদী কবিতা ও উদ্দীপকটি বিবেচনায় মানুষকে বিচার করতে হয়। i. ধর্ম ও বর্ণের ভিত্তিতে ii. মানুষ বিবেচনায় iii. সৃষ্টির উৎস-উপাদান বিবেচনায় নিচের কোনটি ঠিক?,মানুষের যখন পতন আসে তখন পদে পদে ভুল হতে থাকে’ ‘বায়ান্নর দিনগুলো’ প্রবন্ধের এ উক্তিটি প্রকাশ পেয়েছে-i. অভিজ্ঞতা ii. ভাগ্য বিড়ম্বনা iii. ইতিহাসবোধ নিচের কোনটি সঠিক?,গান্ধীজির শেখানো ‘নিজের ওপর অটুট বিশ্বাস’ বলতে ‘আমার পথ’ প্রবন্ধে বোঝানো হয়েছে-,অনুপমের বিয়ে ভাঙার পর মামা মামলা করার পরিকল্পনা করেছিলেন কিসের জন্যে? i. বিবাহের চুক্তিভঙ্গে ii. আর্থিক ক্ষতি পোষাতে iii. মানহানির দাবিতে নিচের কোনটি ঠিক?,গজানন এর সঠিক ব্যাসবাক্য কোনটি?,কবি কাজী নজরুল ইসলামের মৃত্যুদিবস কোনটি?,‘ঐকতান‘ কবিতায় প্রকটভাবে ধরা পড়েছে-i. জ্ঞানের দীনতা ii. ব্যর্থতার স্বরূপ iii. অপূর্ণতার স্বীকারোক্তি নিচের কোনটি ঠিক?,"‘ধান দিয়া কী হইবো, মানুষের জান যদি না থাকে’-কথাটি কে বলেছে?",রবীন্দ্রনাথ ঠাকুর কত সালে সাহিত্যে নোবেল পুস্কার লাভ করেন?,জাতির পিতা বঙ্গবন্ধু শেখ মুজিবুর রহমানের জন্ম দিবস কোনটি?
0,01190002SASA,2021-06-15 17:31:09+06:00,2021-06-15 17:52:49+06:00,0:21:00,77,23.0,30.0,0.0,0.0,1.0,...,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
1,01190003EXAM,2021-06-15 17:30:21+06:00,2021-06-15 17:57:01+06:00,0:25:40,83,25.0,30.0,1.0,0.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
2,01190004HLCR,2021-06-15 17:30:48+06:00,2021-06-15 17:56:44+06:00,0:24:20,67,20.0,30.0,0.0,0.0,1.0,...,1.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
3,01190008MIRA,2021-06-15 17:30:26+06:00,2021-06-15 17:45:05+06:00,0:13:57,63,19.0,30.0,1.0,0.0,1.0,...,1.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0
4,01190010HLCN,2021-06-15 17:57:36+06:00,2021-06-15 18:06:35+06:00,0:07:51,50,15.0,30.0,1.0,0.0,0.0,...,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0